name: AI Orchestration System CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pydantic requests
    - name: Test basic functionality
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from orchestration.core.pool.model_pool import ModelPool
        pool = ModelPool()
        print('Core functionality working')
        "